@startuml
left to right direction

actor Customer
actor Driver

rectangle "Food Ordering App" {

    ' USE CASES
    usecase "Đăng ký" as UC_Register
    usecase "Đăng nhập" as UC_Login

    usecase "Đặt món" as UC_Order
    usecase "Đặt món dùng tại chỗ" as UC_Order_EatIn
    usecase "Đặt món giao tận nơi" as UC_Order_Delivery

    usecase "Thanh toán" as UC_Pay
    usecase "Xác thực thanh toán" as UC_Verify
    usecase "Theo dõi đơn hàng" as UC_Track
    usecase "Hủy đơn hàng" as UC_Cancel

    ' ASSOCIATION
    Customer -- UC_Register
    Customer -- UC_Login
    Customer -- UC_Order
    Customer -- UC_Track
    Driver -- UC_Track

    ' GENERALIZATION (USE CASE LEVEL)
    UC_Order_EatIn -|> UC_Order
    UC_Order_Delivery -|> UC_Order

    ' INCLUDE
    UC_Pay --> UC_Verify : <<include>>

    ' EXTEND
    UC_Cancel ..> UC_Track : <<extend>>

    ' ORDER FLOW
    Customer -- UC_Pay
}

@enduml